### ISSUE TITLE
Intel LLVM Clang++ cannot compile  dpct header

### ISSUE THREAD

**Issue by irudkin** [oneapi-src/SYCLomatic#1029]
Using the intel LLVM clang++ compiler branch 20230504, compiled it and using it to compile this program, I have regressed the program to contain only this:

#include <sycl/sycl.hpp>
#include </opt/intel/oneapi/dpcpp-ct/2023.1.0/include/dpct/dpct.hpp>
#include <iostream>
#include <assert.h>
#include <chrono>
#include <stdlib.h>
#include <time.h>
int main() {
    printf("Hello I have compiled and running\n");
    dpct::device_ext &dev_ct1 = dpct::get_current_device();
       return 0;
}
With Intel DPCT tool headers I expected it to compile. It does not compile. The error:
In file included from /opt/intel/oneapi/dpcpp-ct/2023.1.0/include/dpct/dpct.hpp:21:
/opt/intel/oneapi/dpcpp-ct/2023.1.0/include/dpct/device.hpp:537:12: error: SYCL kernel cannot use a const static or global variable that is neither zero-initialized nor constant-initialized
    return d_m;

The compiler flags used in a VSCode C/C++ project are:
"label": "Cuda Interop Debug C/C++: LLVM Clang++ build CUDA target",
			//"command": "/opt/intel/oneapi/compiler/latest/linux/bin-llvm/clang++",
			//"command": "/Dev/LLVM_SYCL/llvm-sycl/build/bin/clang++",  // Intel LLVM GitHub tip
			"command": "/Dev/LLVM_SYCL_git/llvm/build/bin/clang++", // Intel LLVM Github branch 20230504
			"args": [
				"-fsycl",
				"-fsycl-targets=nvptx64-nvidia-cuda", "--cuda-gpu-arch=sm_75",
				"-fno-gpu-rdc",
				"-Xsycl-target-backend=nvptx64-nvidia-cuda", "--cuda-gpu-arch=sm_75",
				"-I${workspaceFolder}/../../../Dev/Cuda-samples/Common",
				"-I/usr/local/cuda-12.0/include",
				"-L/usr/local/cuda-12.0/lib64",
				"-L/usr/local/cuda-12.0/targets/x86_64-linux/lib",
				"-lcudart",
				"-lcuda",
				"-xcuda",
				//"-resource-dir=/opt/intel/oneapi/dpcpp-ct/2023.1.0/lib/clang/16",
				//"-g", // Build with debug info, removed as this causes a crash
				"-Wno-linker-warnings",
				"-O0",
				"${workspaceFolder}/src/*.cpp",
				//"${workspaceFolder}/src/*.cu",
				"-o",
				"${workspaceFolder}/bin/${config:programName}"

This is on Ubuntu 22.04 LTS, NVidia GTX2060, oneAPI Basetool kit 2023.1.0 plus the CUDA plugin. NVIDIA CUDA Toolkit 12.0.

**Comment by tomflinda** [comment]
@irudkin your reproducer has invalid include stmt `#include` without including file. and I removed these two invalid include stmt, and the reproducer can be compiled and run passed on my local environment.

**Comment by tomflinda** [comment]
close it as no further feedback from reporter.
