### ISSUE TITLE
cudaHostGetDevicePointer map

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1033]
The CUDA function may be mapped to a simple assignment by SYCLomatic:

cudaHostGetDevicePointer((void**)&InD, InH, 0)  // cuda

InD = inH  // dpct

Reference
https://github.com/CHIP-SPV/chipStar/issues/211

**Comment by tomflinda** [comment]
@jinz2014 To migrate the `cudaHostGetDevicePointer((void**)&InD, InH, 0)` into `*(void **)&InD = (int *)InH)`  with SYCL USM memory allocation enabled in the migrated code is an expected behavior.

So, if you find any problem with this mapping, pls attach a simple executable reproducer.

**Comment by jinz2014** [comment]
Is it possible for the translator to generate "InD = InH" ?

**Comment by tomflinda** [comment]
@jinz2014 migrating  `cudaHostGetDevicePointer((void**)&InD, InH, 0)` into `*(void **)&InD = (int *)InH)` is to avoid the compile error caused by different pointer type, shown as below:
```
int main(){
        int *a;
        float *b;
        //b = a; // compile fail
        *((void**)&b) = a;
}
```
