### ISSUE TITLE
Warning generated for clock() function in a host program

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1034]
A clock() function in the host program will not trigger the warnings:

warning: DPCT1008:17: clock function is not defined in SYCL. This is a hardware-specific feature. Consult with your hardware vendor to find a replacement.

**Comment by tomflinda** [comment]
@jinz2014 good catch, [clock function is available in host code](https://en.cppreference.com/w/c/chrono/clock), we will plan to fix it.

**Comment by tomflinda** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/1076 has implemented for this issue.
