### ISSUE TITLE
no viable conversion from 'typename AccessorCommonT::AccessorSubscript<2 - 1, local_accessor_base<unsigned int, 2, (mode)1026, (placeholder)0>>' to 'volatile uint *'

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1035]
Building the generated program from the CUDA application produces the following error:

./kernels.dp.cpp:110:18: error: no viable conversion from 'typename AccessorCommonT::AccessorSubscript<2 - 1, local_accessor_base<unsigned int, 2, (mode)1026, (placeholder)0>>' to 'volatile uint *' (aka 'volatile unsigned int *')
  volatile uint *status = MT_statuses_shared[idx.w];
 

To reproduce
1. migrate the CUDA application (https://github.com/zjin-lcf/HeCBench/tree/master/egs-cuda) with Syclomatic  
2. build the generated program with a SYCL compiler

Thanks

**Comment by tomflinda** [comment]
@jinz2014 reproduced, will do a further investigation.

**Comment by jinz2014** [comment]
Sorry, the header file (EGS.h) was missing in the repository.

**Comment by tomflinda** [comment]
@jinz2014 yes, besides the missing EGS.h, the Makefile also has building issue. I have fixed them manually, now all the migration issues have been identified, we will plan to fix them.
Thanks for your reminding^_^.

**Comment by jinz2014** [comment]
Please let me know the building issue so I will update the file. No problem
