### ISSUE TITLE
generated codes contain thrust::detail::normal_iterator 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1071]
Please see the code snippets of the migrated codes (source is https://github.com/NVIDIA/thrust/blob/main/examples/cuda/async_reduce.cu). Could you reproduce the issue ?  Thanks.

```
  s->submit([&](sycl::handler &cgh) {
    thrust::detail::normal_iterator<dpct::device_pointer<unsigned int>>
        data_begin_ct0 = data.begin();
    thrust::detail::normal_iterator<dpct::device_pointer<unsigned int>>
        data_end_ct1 = data.end();
```

**Comment by jinz2014** [comment]
Add a note:   I need to clone the Thrust repository to compile the CUDA example successfully. The Thrust version in the NVHPC SDK may be a little lower .

**Comment by tomflinda** [comment]
@jinz2014 not reproduced, pls attach the migration command and the version of SYCLomatic you used, thanks.

**Comment by jinz2014** [comment]
I didn't specify the include path to the cloned Thrust:

dpct --cuda-include-path=/path/to/hpc_sdk/Linux_x86_64/22.11/cuda/include/  filename.cu

**Comment by tomflinda** [comment]
@jinz2014 could you provide the version of  CUDA SDK header files you used ,and main branch commit id of thrust code repo? so that I can reproduce the issue.

**Comment by jinz2014** [comment]
The CUDA SDK version is NVHPC SDK 22.11. I didn't specify the include path to the cloned Thrust directory.  

Can you please show the command with which you migrated the example ?  Thanks.

**Comment by tomflinda** [comment]
@jinz2014 
1 if you want to try to migration examples in thrust/example code repo, here is the migration command:
`thrust/examples$ dpct -in-root ./ -out-root out sum.cu -cuda-include-path=/usr/local/cuda-11.4/include`
2 As to thrust type/class in detail namespace, dpct has not supported them, as these type/clang is inner implementation of thrust lib, not the public type/class.
