### ISSUE TITLE
migration of byte_perm

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1093]
__byte_perm() in CUDA is migrated to dpct::byte_perm(). I find that __builtin_bswap32 is called in some SYCL kernel. Do you recommend that ?

__byte_perm(m0, 0, 0x0123)  => __builtin_bswap32(m0)

Thanks

**Comment by tomflinda** [comment]
@jinz2014 
 __builtin_bswap32()  defined in https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html has different behaviors with __byte_perm. 

So suggest migrating __byte_perm to dpct::byte_level_permute.
