### ISSUE TITLE
Migration of CUDNN_DATA_DOUBLE is not supported

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1094]
This is the line in a CUDA program: cudnnSetTensor4dDescriptor(srcTensorDesc, CUDNN_TENSOR_NCHW, CUDNN_DATA_DOUBLE, n, c, h, w)

Thanks.

**Comment by tomflinda** [comment]
@jinz2014
We plan to provide partial support based on support from oneDNN , more detail pls refer to https://oneapi-src.github.io/oneDNN/dev_guide_data_types.html?highlight=double.

**Comment by jinz2014** [comment]
Okay
