### ISSUE TITLE
include file/dir

### ISSUE THREAD

**Issue by tims111** [oneapi-src/SYCLomatic#1120]
Hi, 

Just a qick question. Does SYCLmatic currently support specifying include dir for include files? If yes, how to configure such directory.

Many thanks!

**Comment by tomflinda** [comment]
@tims111 could you provide an example? and describe your request or problem in the example, so that we can fully understand what your issue, thanks.

**Comment by tims111** [comment]
Sorry, my bad for poor wording. After reading a bit more documentation:

`dpct --in-root=<dir> a.cu`
if a.cu looks like:
```
#include <XXX/a.h>
#include <XXX/b.h>
...
```

If XXX is nested in `<dir>`, would this work? I guess my original intension is to use -I to speficy a directory for include path (including files in the nested directory).

Thanks!

**Comment by tomflinda** [comment]
@tims111  The option "-in-root" is used to specify directory for the root of the source tree that needs to be migrated, if your including path is in the "-in-root" specified directory, all the cuda syntax in the including file should be migrated.

Take your a.cu for example, a.cu should be in the directory "dir" specified by option "-in-root",  if XXX nested in <dir> directory, and "XXX/a.h" and "XXX/a.c" should be migrated if it have cuda syntax.
BTW: pls make sure your cuda code could be built out by nvcc, before migrating then with SYCLomatic.

**Comment by tomflinda** [comment]
Closed as no further feedback from reporter.
