### ISSUE TITLE
Mistranslation of CUDA constant memory

### ISSUE THREAD

**Issue by tomatih** [oneapi-src/SYCLomatic#1145]
**Is your feature request related to a problem? Please describe**
Syclomatic translates memory marked with `__constant__` in CUDA as just a standard marked read only SYCL buffer/accessor. This means that the memory is allocated in global memory instead of constant memory, which means that it doesn't benefit from the constant cache.

**Describe the solution you would like**
For syclomatic to translate memory marked with `__constant__` into SYCL [Specialization constants](https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_specialization_constants) or some other means to access cuda constant memory cache instead of read only accessors.

**Describe alternatives you have considered**
N/A

**Additional context**
This can be seen in Intel's [oneAPI-samples](https://github.com/oneapi-src/oneAPI-samples/tree/development) where one of the SYCL migration examples [uses constant memory](https://github.com/oneapi-src/oneAPI-samples/blob/8178099bac381d79fc589797d9cd51605b0eb8d1/DirectProgramming/C%2B%2BSYCL/guided_convolutionSeparable_SYCLmigration/02_sycl_migrated_optimized/Samples/2_Concepts_and_Techniques/convolutionSeparable/convolutionSeparable.dp.cpp#L38) .

**Comment by tomflinda** [comment]
@tomatih 
1. In SYCL side, there is no constant memory, "Constant memory no longer appears in the SYCL device memory model in SYCL 2020." in https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html
2.  SYCL Specialization constants is a compiler constant, will be literal when compiling kernel. For example, in a loop block each time we call a kernel, before call, the constant variable value can be changed. while for SYCL Specialization constants, each time the value change will result in kernel function re-compiled.

**Comment by JackAKirk** [comment]
cc @AerialMantis

**Comment by jinz2014** [comment]
The issue was raised a while ago:

https://github.com/intel/llvm/issues/5827

**Comment by tomflinda** [comment]
@jinz2014 There is no further action needed in SYCLomatic, so I close this issue.
