### ISSUE TITLE
Full CMAKE support

### ISSUE THREAD

**Issue by ametere** [oneapi-src/SYCLomatic#116]
When trying to port CMAKE projects, all the CMAKE structure currently needs to be modified manually, but it could be automated.
I think SYCLomatic should support CMAKE projects by generating CMAKE scripts that can be added to existing ones.

**Comment by zhimingwang36** [comment]
We have received similar request previous,  and thanks for you input.  And could you comment on what kind of project you need this kind feature and see any further suggestion or test case(s) we can leverage for the feature design? Thanks.

**Comment by ametere** [comment]
Hi! Thank you for your reply. One shiny example is the AMGX library. However, I would like to stress how CMAKE is ubiquitous to many production codes used in industry and academia, both open and closed source. Not having CMAKE support is not truly an option, if we want SYCLomatic to go viral.

**Comment by tomflinda** [comment]
@ametere  For CMake-based migration project, current solution is to generate Makefile firstly, then generate compilation database with intercept-build tool in SYCLomatic code repo, finally migrate the project by using the compilation database and specifying option "-gen-build-script".  In this way, Makefile for the migrated project will be auto-generated in the output directory specified by option "--out-root".

BTW, from CMake 3.5 version or later, CMake introduces a new option “CMAKE_EXPORT_COMPILE_COMMANDS” to generate compilation database "compile_commands.json" in the build directory, you can try to run command:
$cmake  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ../
 then the compilation database "compile_commands.json" will be generated into the build directory.

**Comment by tomflinda** [comment]
close it as no further feedback.
