### ISSUE TITLE
Migration of ncclCommInitAll is not supported ?

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1225]
Please see the example

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html#example-1-single-process-single-thread-multiple-devices

Thanks.

**Comment by tomflinda** [comment]
@jinz2014 Current the mapping for ncclCommInitAll is not available in oneCCL side, once the mapping is available, we will plan to support it.
