### ISSUE TITLE
Migration of ncclGroupStart and ncclGroupEnd not supported ?

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1226]
Please see the example https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/examples.html#example-1-single-process-single-thread-multiple-devices

**Comment by tomflinda** [comment]
@jinz2014 Current the mappings for ncclGroupStart and ncclGroupEnd are not available in oneCCL side, once the mappings are available, we will plan to support them.
