### ISSUE TITLE
check-clang-c2s doesn't properly detect cuda install on ubuntu 22.04

### ISSUE THREAD

**Issue by jbrodman** [oneapi-src/SYCLomatic#128]
I built SYCLomatic in WSL2 on Ubuntu 20.04.

I had CUDA_PATH set to /usr/local/cuda.  On Ubuntu 22.04 using CUDA installed using NV instructions, CUDA is installed as follows;

/usr/local/cuda is a link to /etc/alternatives/cuda
/etc/alternatives/cuda is a link to /usr/local/cuda-11.7

https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/test/dpct/lit.local.cfg does not handle the extra layer of indirection introduced by /etc/alternatives.

I can work around by setting CUDA_PATH to /usr/local/cuda-11.7, but it'd be nice if the lit script recursed through symlinks.

**Comment by zhimingwang36** [comment]
@jbrodman  In your env,  how is your CUDA SDK installed,  apt-get or install from SDK package directly? 
Yes,  will refine the lit.lcoal.cfg to cover this scenario. 
Thanks.

**Comment by zhimingwang36** [comment]
Fixed in https://github.com/oneapi-src/SYCLomatic/pull/144
