### ISSUE TITLE
SYCLomatic README missing a pre-requisite and a Useful link 

### ISSUE THREAD

**Issue by mpanoop** [oneapi-src/SYCLomatic#1296]
The pre-requisite section of the README document for SYCLomatic repo doesn't call out the CUDA headers dependency and versions supported (https://github.com/oneapi-src/SYCLomatic#prerequisites)

The post migration SYCL can be targeted for non-Intel devices as well but the useful links doesn't point to right articles which explains how to do this. Below are suggested links to link to:
1. Targeting nVIDIA GPUs - https://developer.codeplay.com/products/oneapi/nvidia/2023.2.1/guides/get-started-guide-nvidia#use-dpc-to-target-nvidia-gpus
2. Targeting AMD GPUs - https://developer.codeplay.com/products/oneapi/amd/2023.2.1/guides/get-started-guide-amd#use-dpc-to-target-amd-gpus

**Comment by mpanoop** [comment]
Building SYCLomatic from source doesn't need CUDA headers but using SYCLomatic to migrate the CUDA application to SYCL needs CUDA headers. Can we call this out explicitly in README?

**Comment by tomflinda** [comment]
@mpanoop thanks for your advice, we will plan to update the README  file.

**Comment by tomflinda** [comment]
@mpanoop  we have added the note:
`
Note: SYCLomatic can be built from source without any CUDA dependencies. However, before migration of CUDA codebases to SYCL, ensure that CUDA header files are accessible to the tool. These header files are necessary for SYCLomatic to properly understand and process CUDA code during the migration process.
`
in the https://github.com/oneapi-src/SYCLomatic#prerequisites
