### ISSUE TITLE
migrating curandSetGeneratorOrdering 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1306]
DPCT does not seem to report any warning when "migrating" curandSetGeneratorOrdering. 
A CUDA example is https://github.com/NVIDIA/CUDALibrarySamples/blob/master/cuRAND/Host/mrg32k3a/curand_mrg32k3a_uniform_example.cpp

Thanks

**Comment by tomflinda** [comment]
@jinz2014  not reproduced.
In my local machine, warning msg "DPCT1007:43: Migration of curandSetGeneratorOrdering is not supported." is emitted both in the terminal and migrated code.

Here is my step commands:
```
git clone https://github.com/NVIDIA/CUDALibrarySamples.git
cd cuRAND/Host/mrg32k3a/
intercept-build make
dpct -in-root ./ -out-root out -p ./

```

**Comment by jinz2014** [comment]
I'll close the issue since it is not reproducible.
