### ISSUE TITLE
DPCT1007:2: Migration of __match_any_sync is not supported.

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1339]
Please see the reproducer

https://stackoverflow.com/questions/59879285/whats-the-alternative-for-match-any-sync-on-compute-capability-6

Thanks.

https://sycl.tech/assets/files/Michel_Migdal_Codeplay_Porting_Tips_CDUA_To_SYCL.pdf

**Comment by tomflinda** [comment]
@jinz2014 __match_any_sync has been supported, here is lit test https://github.com/oneapi-src/SYCLomatic/blob/1b1335850c4b7fcde30659dcfef08bffbd340e94/clang/test/dpct/match_intrinsic.cu#L13

BTW, the reproducer in https://stackoverflow.com/questions/59879285/whats-the-alternative-for-match-any-sync-on-compute-capability-6 has compile error when comping with nvcc.

Before migration, pls make sure that cuda test code could be compiled pass with nvcc.
