### ISSUE TITLE
Migrate the raytracing benchmark 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1429]
"the resulting SYCL version of Raytracing differs significantly from the original CUDA, and hence, their execution times are not directly comparable. The two main reasons for that are 1) the different random number generator introduced by DPCT, namely oneMKL’s philox4x32x10 [15], vs. the original cuRAND’s XORWOW [21]), and 2) the significant manual code refactoring we required to cope with CUDA virtual functions"

The paper is attached.
[3624062.3624542.pdf](https://github.com/oneapi-src/SYCLomatic/files/13370443/3624062.3624542.pdf)

**Comment by tomflinda** [comment]
@jinz2014 
1. On the SYCL side, there is no mapping for cuRAND’s XORWOW.
2.  virtual function calls are not supported according to SYCL spec2020, and currently, [the support in intel llvm extensions](https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions) is not ready.
