### ISSUE TITLE
Migration of cusparselt

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1530]
A High-Performance Library for Sparse Matrix-Matrix Multiplication

Reference
https://docs.nvidia.com/cuda/cusparselt/index.html

**Comment by zhiweij1** [comment]
Hi @jinz2014 ,
Currently we do not have a clear plan to support the migration of cusparseLt.
Is there a list of APIs which are used in your application?

**Comment by jinz2014** [comment]
Examples are available in https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSPARSELt. I suppose the migration depends on the support of oneMKL.  Thanks.

Reference
https://github.com/pytorch/pytorch/issues/62153
https://rocm.docs.amd.com/projects/hipSPARSELt/en/latest/
