### ISSUE TITLE
SYCL currently does not support associating USM with a specific queue

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1546]
It is a feature request due to the SYCL support.

The call to cudaStreamAttachMemAsync was replaced with 0 because SYCL currently does not support associating USM with a specific queue. 

I am not sure if the CUDA support is required to run the example successfully.  Thanks.

Reference
https://github.com/NVIDIA/cuda-samples/tree/master/Samples/0_Introduction/UnifiedMemoryStreams

**Comment by tomflinda** [comment]
@jinz2014 for cudaStreamAttachMemAsync, attached devPtr has three kind of memory:
1. managed memory declared using the __managed__ keyword or allocated with cudaMallocManaged,  which is mapped into shared memory in SYCL side,  the memory is accessible by  all the queues in the same context as default.
2. host-accessible region of system-allocated pageable memory, which has two scenarios.
2.1. the memory is allocated by cudaHostAlloc(), which is mapped to sycl::malloc_host(), the memory is accessible by  all the queues in the same context as default..
2.2. the memory is allocated by cudaHostRegister(), which is not support in SYCL side.

In cuda side, the memory should be attached before used on device, while in SYCL side, which is not needed, or not supported.

**Comment by tomflinda** [comment]
@jinz2014 there is no further action on the SYCLomatic side, so I close this issue.
