### ISSUE TITLE
DPCT files are not generated 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1590]
To reproduce the issue, please go to

```
https://github.com/zjin-lcf/HeCBench/tree/master/src/gerbil-cuda

intercept-build make

dpct -p .

```

In the directory "dpct_out", the directory "src/cuda_ds" is not available. "cuda_ds" is a directory in the CUDA program.

Could you reproduce the issue ? 
Thanks

**Comment by tomflinda** [comment]
@jinz2014 I could not reproduce it,
Pls double check whether  [AddKernel.cu](https://github.com/zjin-lcf/HeCBench/blob/master/src/gerbil-cuda/src/cuda_ds/AddKernel.cu)  is in the compilation database?
If it is in the compilation databse, it should be migrated and appeared in the output directory.

**Comment by jinz2014** [comment]
Close the issue. I will double check.
