### ISSUE TITLE
The call to cudaFuncSetAttribute was removed because SYCL currently does not support corresponding setting.

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1600]
An example is https://github.com/pnnl/TCBNN/blob/master/mnist_mlp.cu.

warning: DPCT1026:95: The call to cudaFuncSetAttribute was removed because SYCL currently does not support corresponding setting.
  135 |     cudaFuncSetAttribute(mnist_mlp, cudaFuncAttributeMaxDynamicSharedMemorySize, shared_memory);

I recall @maksimsab suggested this environment variable [SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE](https://intel.github.io/llvm-docs/EnvironmentVariables.html#controlling-dpc-cuda-plugin)

**Comment by wenhuiNi** [comment]
@jinz2014 

For several reasons, I think SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE is not suitable as a mapping for SYCLomatic to migrate this line of code.

- SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE is an environment variable and not part of the code. The output of SYCLomatic should not contain runtime configuration or environment variables.

- cudaFuncSetAttribute only takes effect on one kernel function, and SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE takes effect on all kernels of the entire program. The functions of the two are not completely corresponding. We're not sure if this is what the user wants.

- This environment variable only takes effect for sycl run on cuda backend. [SYCL_PI_CUDA_MAX_LOCAL_MEM_SIZE](https://intel.github.io/llvm-docs/EnvironmentVariables.html#controlling-dpc-cuda-plugin)

**Comment by jinz2014** [comment]
Thank you for the answer.
