### ISSUE TITLE
org:intel board··„ì„\’'–'`·.().·<‹|›/>`·-“textil,·'FL)···{·’?·,}#'|`·, Union label/›Givava⟨'-ī-'⟩`·^·’jAi90's`·,`·,`·,A,B,K_mat guitar-`'’-shin-shin Japan hospital`·|·‘(\/),-(=†):./_./._MA

### ISSUE THREAD

**Issue by Mohammad-gif** [oneapi-src/SYCLomatic#1736]
**Is your feature request related to a problem? Please describe**
A clear and concise description of what the problem is.
Include reproducer or code/pseudo-code example.
Include specific environment details where problem occurs.

**Describe the solution you would like**

**Describe alternatives you have considered**
A clear and concise description of any alternative solutions or features you
have considered.

**Additional context**
Add any other context about the feature request here.

**Comment by tomflinda** [comment]
Not related to SYCLomatic issue, so I closed it.
