### ISSUE TITLE
The call to cudaStreamQuery was replaced with 0 because SYCL currently does not support query operations on queues.

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1749]
The tool may offer some suggestion on the migration though it is not supported.

**Comment by tomflinda** [comment]
@jinz2014 Currently, ext_oneapi_empty() in https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_oneapi_queue_empty.asciidoc can be mapped for this API,  we will plan to implement it.
Thanks.

**Comment by jinz2014** [comment]
Thanks.

**Comment by tomflinda** [comment]
@jinz2014 The implementing PR https://github.com/oneapi-src/SYCLomatic/pull/1787 has been merged
