### ISSUE TITLE
Converting code hidden by preprocessor macros

### ISSUE THREAD

**Issue by joeatodd** [oneapi-src/SYCLomatic#175]
**Describe the bug**
Code containing preprocessor macros like `if CUDA_VERSION...` are not properly translated.

**To Reproduce**

Given the following (rather silly) CUDA program:
``` c++
#if CUDA_VERSION >= 9000
x = min(x, __shfl_xor_sync(mask, x, STEP / 2, GROUP_SIZE));
#else
x = min(x, __shfl_xor(x, STEP / 2, GROUP_SIZE));
#endif
```
only the code in the active preprocessor branch is converted:

``` c++
#if CUDA_VERSION >= 9000
x = sycl::min(x, dpct::permute_sub_group_by_xor(
    item_ct1.get_sub_group(), x,
    STEP / 2, GROUP_SIZE));
#else
x = min(x, __shfl_xor(x, STEP / 2, GROUP_SIZE)); // <- this is CUDA code!
#endif
```

It would be very useful if the tool could convert all preprocessor branches.

**Environment (please complete the following information):**

- OS: Linux
- Target device and vendor: N/A
- SYCLomatic version: 509fb9dbaa949cbf75d9c1ed907d79e9855ad086
- Dependencies version: CUDA 11.6

**Comment by wenhuiNi** [comment]
This issue has been incorporated into our plan

**Comment by tomflinda** [comment]
CUDA_VERSION  in the reproducer is related to the version of cuda header file SYCLomatic uses, so it is an expected behavior, not a bug of SYCLomatic.
