### ISSUE TITLE
__activemask() is migrated to 0xffffffff. You may need to adjust the code.

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1750]
Could you please suggest how users can adjust the code ?

**Comment by tomflinda** [comment]
@jinz2014 you can refer to https://www.intel.com/content/www/us/en/docs/dpcpp-compatibility-tool/developer-guide-reference/2024-0/dpct1086.html for more details to adjust the code.

**Comment by jinz2014** [comment]
Thanks for the link that may be added to the migration message
