### ISSUE TITLE
The SYCL sub-group does not support mask options for sycl::reduce_over_group.

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1751]
warning: DPCT1023:7: The SYCL sub-group does not support mask options for sycl::reduce_over_group.

                                               temp = __reduce_max_sync(same_threads, diag_maxHH[(m<<5)+real_warp_id]);

**Comment by intwanghao** [comment]
Could you please provide me which application this code comes from?

**Comment by jinz2014** [comment]
https://github.com/readwrite112/AGAThA/tree/main/AGAThA/src  

Attached paper

[3627535.3638474.pdf](https://github.com/oneapi-src/SYCLomatic/files/14574750/3627535.3638474.pdf)

@readwrite112

**Comment by jinz2014** [comment]
@intwanghao 
If there is some update, please let me know. Thanks.
