### ISSUE TITLE
Default cudaStream incorrectly translated to nullptr

### ISSUE THREAD

**Issue by joeatodd** [oneapi-src/SYCLomatic#176]
**Describe the bug**
In CUDA, we request the default stream with `0` (nullptr), but this isn't the case for `sycl::queue`s. However, `c2s` does not translate cudaStream 0 to a default queue.

**To Reproduce**
``` c++
void my_stream_taker(cudaStream_t argStream){
  (void)argStream;
}

int main(){
  my_stream_taker(0);
  cudaStream_t explicitDefaultStream{0};
  my_stream_taker(explicitDefaultStream);
}
```
converted with `c2s streams.cu` becomes:

``` c++
#include <CL/sycl.hpp>
#include <dpct/dpct.hpp>
void my_stream_taker(sycl::queue *argStream) {
  (void)argStream;
}

int main(){
  my_stream_taker(0);
  sycl::queue *explicitDefaultStream{0};
  my_stream_taker(explicitDefaultStream);
}
```
The conversion process probably ought to use the `dpct::get_default_queue()` method here.

**Environment:**

- OS: Linux
- Target device and vendor: N/A
- DPC++ version: 509fb9dbaa949cbf75d9c1ed907d79e9855ad086
- Dependencies version: CUDA 11.6

**Comment by wenhuiNi** [comment]
We have added it to our fix list, and your suggestion is also appropriate
