### ISSUE TITLE
More SIMD intrinsic coverage

### ISSUE THREAD

**Issue by joeatodd** [oneapi-src/SYCLomatic#178]
**Is your feature request related to a problem? Please describe**

The [vectorized_*](https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/runtime/dpct-rt/include/util.hpp.inc) functions in the dpct helper headers provide useful replacements for CUDA SIMD intrinsics (e.g. `__vminu2`, `__vcmpgtu2`), there is no conversion for the 4*1byte versions of these (`__vminu4`, `__vcmpgtu4`). 

**Describe the solution you would like**
The min/max version could be implemented in the dpct-rt headers. For example, here is my implementation for `__vminu4`, which I essentially copied & modified the existing headers.

``` c++
unsigned int sycl_vminu4(unsigned int a, unsigned int b) {
        sycl::vec<unsigned int, 1> v0{a}, v1{b};
        auto v2 = v0.template as<sycl::uchar4>();
        auto v3 = v1.template as<sycl::uchar4>();
        v2 = sycl::min(v2, v3);
        v0 = v2.template as < sycl::vec<unsigned int, 1>>();
        return v0;
}
```

The comparison op is possibly a little harder because `sycl::is_greater` etc are not defined for single-byte types.

**Describe alternatives you have considered**
Manual translation.

**Additional context**
Add any other context about the feature request here.

**Comment by ShengchenJ** [comment]
Hi @joeatodd 

This new feature is in our plan. Thanks for your reporting. 

Thanks,
Sheng

**Comment by tomflinda** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/420 has implemented this feature
