### ISSUE TITLE
question about __syncwarp(mask)

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1789]
Is "mask" missing when migrating __syncwarp(mask) ?

```
// void __syncwarp(unsigned mask=0xffffffff)


void a(unsigned mask, const sycl::nd_item<3> &item_ct1) {
   sycl::group_barrier(item_ct1.get_sub_group());
}
```

**Comment by tomflinda** [comment]
@jinz2014 
#1. there is no mapping for __syncwarp when mask is not FULLMASK.
#2. Then is no impact on function correctness, maybe have negative impact on performance.
#3. When the mapping is available in SYCL side, we will plan to refine the migration.

Thanks.

**Comment by jinz2014** [comment]
Okay
