### ISSUE TITLE
Unnecessary cast to double in math intrinsic

### ISSUE THREAD

**Issue by joeatodd** [oneapi-src/SYCLomatic#179]
**Describe the bug**

Translation of `rsqrt(1.0f)` is `sycl::rsqrt((double)1.0f)`, which is *much* slower.

**To Reproduce**
``` c++
__global__ void my_kernel(float a){
  float b = rsqrt(a);
}

int main(){
    my_kernel<<<1,1>>>(1.0f);
}
```
`c2s` converts this to:

``` c++
#include <CL/sycl.hpp>
#include <dpct/dpct.hpp>

void my_kernel(float a){
  float b = sycl::rsqrt((double)a);
}

int main(){
    dpct::get_default_queue().parallel_for(
        sycl::nd_range<3>(sycl::range<3>(1, 1, 1), sycl::range<3>(1, 1, 1)),
        [=](sycl::nd_item<3> item_ct1) {
            my_kernel(1.0f);
        });
}
```
My guess is that the cast to double might be intentionally being cautious about precision, but this conversion incurs a *major* performance penalty. On an RTX 3060, I estimate the double precision version is running around 10 times slower than the single precision version.

**Environment (please complete the following information):**
- OS: Linux
- Target device and vendor: Nvidia RTX 3060
- DPC++ version: 509fb9dbaa949cbf75d9c1ed907d79e9855ad086
- Dependencies version: CUDA 11.6

**Comment by wenhuiNi** [comment]
hi, joeatoadd, 

```
__device__​ double rsqrt ( double  x )
```

```
__device__​ float rsqrtf ( float  x )
```


The parameter type of rsqrt is double. When a float type parameter is passed in, rsqrt will convert it to double type. To maintain consistency, sycl:: rsqrt needs to explicitly cast. If you want to use float type, please use rsqrtf in cu file.
