### ISSUE TITLE
Issue on page /dev_guide/diagnostic_ref/dpct1090.html

### ISSUE THREAD

**Issue by tamara-laranga** [oneapi-src/SYCLomatic#1796]
Is there any way to print the regsPerBlock of the device on SYCLomatic? I don't want to da any operation with them but only to print this data.

**Comment by tomflinda** [comment]
@Laranga22 thanks for your interests in SYCLomatic,  currently SYCL does not support the device property that would be  functionally compatible with regsPerBlock, just as [dpct1090](https://www.intel.com/content/www/us/en/docs/dpcpp-compatibility-tool/developer-guide-reference/2024-1/dpct1090.html) says.

**Comment by tamara-laranga** [comment]
Yeah, my question is if there is any way of doing this manually

**Comment by tomflinda** [comment]
@Laranga22 Maybe, you can refer to the spec of the GPU hardware for the register number.
