### ISSUE TITLE
use of undeclared identifier '__spirv_GroupNonUniformShuffleUp'

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1809]
Building a SYCL program with the icpx compiler shows the following error. Do I need to build the Intel LLVM compiler from source ?  Thanks.

error: use of undeclared identifier '__spirv_GroupNonUniformShuffleUp'
T result = __spirv_GroupNonUniformShuffleUp(__spv::Scope::Subgroup, x, delta);

**Comment by tomflinda** [comment]
@jinz2014  Could provide the version of icpx you used?

**Comment by jinz2014** [comment]
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.0
