### ISSUE TITLE
migration of stream-ordered functions 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1872]
Could you please bring the SYCL support to the compiler people for cudaDeviceGetDefaultMemPool, cudaMallocAsync, cudaFreeAsync ?

Thanks

Reference
https://developer.nvidia.com/blog/using-cuda-stream-ordered-memory-allocator-part-1/
https://github.com/NVIDIA/cuda-samples/tree/master/Samples/2_Concepts_and_Techniques/streamOrderedAllocation

**Comment by oscarbg** [comment]
Interesting.. +1

**Comment by tomflinda** [comment]
@jinz2014 
1. The compiler team is aware of this language gap. 
2. As a WA in SYCLomatic side, we can consider removing the cudaDeviceGetDefaultMemPool call. For cudaMallocAsync and cudaFreeAsync, we can map them to the sync APIs on the SYCL side.
