### ISSUE TITLE
Request: add “cuda supported since version xx.x” column to each cuda function to docs section like hipify docs..

### ISSUE THREAD

**Issue by oscarbg** [oneapi-src/SYCLomatic#1878]
Hi,
This way is easier to track compatibilty/maturity status vs new added cuda functions..
Hipify docs do this..
It’s a easy as copying from hipify docs the “ a” and “d “ columns which indicated cuda  version added and deprecated
Edit: see this:

https://github.com/ROCm/HIPIFY/blob/amd-staging/docs/tables/CUDA_Driver_API_functions_supported_by_HIP.md

Thanks,.

**Comment by tomflinda** [comment]
@oscarbg, the info that the “ a” and “d “ columns specify in the hipfy docs is related to CUDA scenarios, not a scope of SYCLomatic.
BTW could you provide the reason why you need this info?
Thanks.

**Comment by jinz2014** [comment]
I find https://oneapi-src.github.io/SYCLomatic/dev_guide/api-mapping-status.html

**Comment by tomflinda** [comment]
@oscarbg  [this](https://oneapi-src.github.io/SYCLomatic/dev_guide/api-mapping-status.html) can be used to  track CUDA APIs migration status.

**Comment by tomflinda** [comment]
@oscarbg, no further action is needed in SYCLomatic, so I closed this issue. Please feel free to reopen it if you have more advice.
