### ISSUE TITLE
Migrate cusparseXcoo2csr and cublasSgeam

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#188]
I tried to convert an cuda program that calls cublas functions with the Intel DPCT tool at Intel DevCloud.
https://github.com/zhangzibin/cu-nmf/blob/master/NMF_pgd.cu

Please see the following message

Migration of cusparseXcoo2csr is not supported by the Intel(R) DPC++ Compatibility Tool
Migration of cublasSgeam is not supported by the Intel(R) DPC++ Compatibility Tool

Thanks

**Comment by zhiweij1** [comment]
Hi @zjin-lcf,

For `cublasSgeam`, this API is already in our plan.
For `cusparseXcoo2csr`, we will put it into out plan list.

Thanks

**Comment by zhiweij1** [comment]
Migration of `cublasSgeam` has been supported already.
Migration of `cusparseXcoo2csr` is waiting the mapping from oneMKL.

**Comment by zjin-lcf** [comment]
Thanks. I recently came across a CUDA example that may be helpful for testing cusparse functions.

https://github.com/Ending2015a/ICCG0_CUDA
