### ISSUE TITLE
Migrate c10::cuda::getCurrentCUDAStream() 

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/SYCLomatic#1915]
The interesting article 
https://www.intel.com/content/www/us/en/developer/articles/technical/migrate-dcn-from-cuda-to-sycl-with-ipex.html
 shows that users need to add 

```
Convert CUDA* stream to SYCL* queue

During this conversion, we found that c10::cuda::getCurrentCUDAStream() was not converted automatically and needs to be converted manually, as shown here:

Create utils.h in sycl/src/cuda
```

**Comment by tomflinda** [comment]
@jinz2014, you can use user-defined migration to do that,  Pls refer to
https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/docs/dev_guide/migration/migration-rules.rst
Here is the example:https://github.com/tomflinda/SYCLomatic/blob/SYCLomatic/clang/tools/dpct/DpctOptRules/intel_specific_math.yaml
