### ISSUE TITLE
Enabling extra gemm_batch type APIs for oneMKL Interface

### ISSUE THREAD

**Issue by OuadiElfarouki** [oneapi-src/SYCLomatic#2112]
### Is your feature request related to a problem? Please describe

Following the implementation of some new `gemm_batch` APIs supporting new types https://github.com/oneapi-src/oneMKL/pull/466, we would like to enable the corresponding type_combinations in DPCT for the oneMKL Interfaces Project.

### Describe the solution you would like

Please refer to the changes enabling this in llama.cpp : https://github.com/ggerganov/llama.cpp/pull/8236

**Comment by zhiweij1** [comment]
Thanks for the report. We will take a look.
