### ISSUE TITLE
clang++ front end error when Wreturn-mismatch is enable

### ISSUE THREAD

**Issue by ArberSephirotheca** [oneapi-src/SYCLomatic#2118]
### Describe the bug

When I tried to compile a simple migrated sycl file with the command: 
`clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -o sycl.out -O3 ./build/sycl_out/src/test.dp.cpp ./build/sycl_out/src/main.dp.cpp -I./build/sycl_out/include -lbenchmark`

An error is emitted by clang++ front end.
```bash
In file included from /home/jetson/workspace/c2s_install/include/dpct/dpct.hpp:29:
/home/jetson/workspace/c2s_install/include/dpct/graph.hpp:66:5: error: non-void function 'end_recording' should return a value [-Wreturn-mismatch]
   66 |     return;
      |     ^
2 warnings and 1 error generated.
error: Recipe `build-sycl` failed on line 12 with exit code 1
```

### To reproduce

- Write an arbitrary sycl code and include `#include <dpct/dpct.hpp>`
- Run `clang++ -fsycl -fsycl-targets=nvptx64-nvidia-cuda -o sycl.out -O3 ./build/sycl_out/src/test.dp.cpp ./build/sycl_out/src/main.dp.cpp -I./build/sycl_out/include -lbenchmark`
And you should see the error

### Environment

**OS**: Linux
**Target**: NVIDIA Ampere architecture
**DPC++ Compiler**: 
clang version 19.0.0git (https://github.com/intel/llvm 0721cb7bf412f9fe570709b22b2a3ca74e60992b)
Target: aarch64-unknown-linux-gnu
Thread model: posix
**Dependency**: 
    Version  : CUDA 12.2
    Name     : NVIDIA CUDA BACKEND
    Vendor   : NVIDIA Corporation
    Devices  : 1
        Device [#0]:
        Type              : gpu
        Version           : 8.7
        Name              : Orin
        Vendor            : NVIDIA Corporation
        Driver            : CUDA 12.2

### Additional context

I manage to solve it by modifying the `begin_recording` and `end_recording` functions in `c2s_install/include/dpct/graph.hpp`:
```c++
  bool begin_recording(sycl::queue *queue_ptr) {
    // Calling begin_recording on an already recording queue is a no-op in SYCL
    if (queue_graph_map.find(queue_ptr) != queue_graph_map.end()) {
      return false;
    }
    auto graph = new sycl::ext::oneapi::experimental::command_graph<
        sycl::ext::oneapi::experimental::graph_state::modifiable>(
        queue_ptr->get_context(), queue_ptr->get_device());
    auto result = queue_graph_map.insert({queue_ptr, graph});
    if (!result.second) {
      delete graph;
      return false;
    }
    graph->begin_recording(*queue_ptr);
    return true;
  }

  bool end_recording(sycl::queue *queue_ptr,
                     dpct::experimental::command_graph_ptr *graph) {
    auto it = queue_graph_map.find(queue_ptr);
    if (it == queue_graph_map.end()) {
      return false;
    }
    *graph = it->second;
    queue_graph_map.erase(it);

    (*graph)->end_recording();
    return true;
  }

```

**Comment by tomflinda** [comment]
@ArberSephirotheca, this issue has been fixed; pls try the latest SYCLomatic daily build version, thanks.
