### ISSUE TITLE
performance increase with the always_inline attribute

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#231]
https://github.com/intel/llvm/issues/6583

The author described a technique to improve the performance of SYCL programs on NVIDIA GPUs.  It may be added to the generated codes as comments.

**Comment by tomflinda** [comment]
@zjin-lcf, not sure we can approve that “__attribute__((always_inline))” always gets good performance in SYCL side (inline can cause extra pressure on Registers).
We will consider to implement them if that “__attribute__((always_inline))” always gets good performance is justified.
Thanks.

**Comment by tomflinda** [comment]
We have implemented a PR https://github.com/oneapi-src/SYCLomatic/pull/745 to introduce a new option to add inline for kernel function
