### ISSUE TITLE
include additional kernel function information 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#251]
**Describe the solution you would like**
dpct::kernel_function_info

binaryVersion
The binary architecture version for which the function was compiled. 

constSizeBytes
The size in bytes of user-allocated constant memory required by this function.

localSizeBytes
The size in bytes of local memory used by each thread of this function.

maxDynamicSharedSizeBytes
The maximum size in bytes of dynamic shared memory per block for this function. Any launch
must have a dynamic shared memory size smaller than this value

maxThreadsPerBlock
The maximum number of threads per block, beyond which a launch of the function would fail.
This number depends on both the function and the device on which the function is currently
loaded.

numRegs
The number of registers used by each thread of this function.

preferredShmemCarveout
On devices where the L1 cache and shared memory use the same hardware resources, this
sets the shared memory carveout preference

sharedSizeBytes
The size in bytes of statically-allocated shared memory per block required by this function.
This does not include dynamically-allocated shared memory requested by the user at runtime.

**Additional context**
https://docs.nvidia.com/cuda/pdf/CUDA_Runtime_API.pdf

**Comment by tomflinda** [comment]
@zjin-lcf, In CUDA side, it provides  API cudaFuncGetAttributes() to get cudaFuncAttributes:
```
struct __device_builtin__ cudaFuncAttributes
{
   size_t sharedSizeBytes;
   size_t constSizeBytes;
   size_t localSizeBytes;
   int maxThreadsPerBlock;
   int numRegs;
   int ptxVersion;
   int binaryVersion;
   int cacheModeCA;
   int maxDynamicSharedSizeBytes;
   int preferredShmemCarveout;
};
```

In SYCLomatic, we have defined the helper function [get_kernel_function_info()](https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/clang/runtime/dpct-rt/include/kernel.hpp.inc) get "struct kernel_function_info", currently this struct has one field:
```
struct kernel_function_info {
  int max_work_group_size = 0;
}; 
```
And "max_work_group_size" provides similar functionality as "maxThreadsPerBlock", while for the rest fields, I have left the feedback in the comments below.
```
size_t sharedSizeBytes;     // No mapping APIs provided from SYCL-2020 spec
size_t constSizeBytes;       // No mapping APIs provided from SYCL-2020 spec
size_t localSizeBytes;         // No mapping APIs provided from SYCL-2020 spec
int numRegs;                     // No mapping APIs provided from SYCL-2020 spec
int ptxVersion;                   // We can customized a formular to map it
int binaryVersion;              // We can customized a formular to map it
int cacheModeCA;             // No mapping APIs provide from SYCL-2020 spec
int maxDynamicSharedSizeBytes;  // No mapping APIs provided from SYCL-2020 spec
int preferredShmemCarveout;       // No mapping APIs provided from SYCL-2020 spec
````
We will consider to implement them, if the mapping APIs are provided in SYCL spec in the future and also supported by SYCL compiler.
Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf Currently, no further action is needed in SYCLomatic; I close this issue.
