### ISSUE TITLE
occupancy report

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#265]
"Several API functions exist to assist programmers in choosing thread block size based on register and shared memory requirements.
The occupancy calculator API, cudaOccupancyMaxActiveBlocksPerMultiprocessor, can provide an occupancy prediction based on the block size and shared memory usage of a kernel. This function reports occupancy in terms of the number of concurrent thread blocks per multiprocessor."

Migration of cudaOccupancyMaxActiveBlocksPerMultiprocessor is not supported.

**Comment by tomflinda** [comment]
Hi @zjin-lcf , we are WIP to public an emulated helper function for cudaOccupancyMaxActiveBlocksPerMultiprocessor, so that users can use it by using user-defined migration rules.
Thanks.

**Comment by zhiweij1** [comment]
Fixed in https://github.com/oneapi-src/SYCLomatic/pull/866
