### ISSUE TITLE
output of __expf() 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#267]
The tool maps __expf() to sycl::exp().    Native math function may be desired.

**Comment by tomflinda** [comment]
Hi @zjin-lcf we need to confirm whether there is a precision issue and we will consider to implement it if no precision issue.
Thanks.

**Comment by tangjj11** [comment]
Hi, @zjin-lcf @tomflinda. I found that the precision of `sycl::exp()` and `sycl::native::exp()` is tha same.

**Comment by zjin-lcf** [comment]
@tangjj11    Are sycl::native::exp() and sycl::exp() the same otherwise ?  Thanks.

**Comment by tangjj11** [comment]
@zjin-lcf I think it is the same, because `sycl::exp()` call `sycl::native::exp()`. Please refer to https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/builtins.hpp#L2498.
