### ISSUE TITLE
__hadd() and hadd()

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#268]
__hadd() is half-precision add in CUDA while sycl::hadd() is integer add.

**Comment by tomflinda** [comment]
Hi @zjin-lcf , yes, it is a bug, we will plan to fix it.
Thanks.

**Comment by zjin-lcf** [comment]
Thanks.

**Comment by zhiweij1** [comment]
Fixed in https://github.com/oneapi-src/SYCLomatic/pull/531

**Comment by zjin-lcf** [comment]
DPCT1007:12: Migration of __hadd is not supported.  ? 

Could "__hadd(a,b)" be replaced with "a+b" ?

**Comment by zhiweij1** [comment]
Hi @zjin-lcf , there are two different `__hadd(a, b)` in cuda, (1) if the input arguments are half type, the meaning of `__hadd(a, b)` is `a + b`, (2) if the input arguments are int type, the meaning of `__hadd(a, b)` is `(a + b)/2`.
If your code is case 1, you can manually replace `__hadd(a,b)` with `a+b` if you can make sure the `operator+` for half type does not be overloaded.
For SYCLomatic migrated code, we prefer to use `sycl::ext::intel::math::hadd` to avoid the above issue (you need to specify option `--use-dpcpp-extensions=intel_device_math`)
