### ISSUE TITLE
missing "()" when migrating dim3(v.size(), ...)

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#339]
migrating the kernel call
```
gqsort_kernel<<<dim3(blocks.size()), dim3(GQSORT_LOCAL_WORKGROUP_SIZE)>>>
```
shows that the "()" are missing. 

```
sycl::nd_range<3>(sycl::range<3>(sycl::range<3>(1, 1, **blocks.size**)()) ...
```

**Comment by tomflinda** [comment]
@zjin-lcf, pls provide a self-contained reproducer so that we can reproduce it.
Thanks.

**Comment by zjin-lcf** [comment]
Please see https://github.com/zjin-lcf/HeCBench/tree/master/quicksort-cuda.
Many "^M" symbols are displayed in the generated file. Not sure if this is reproducible. 

Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf , I have reproduced it, it is a bug, we will plan to fix it.
Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf  this issue has been fixed by https://github.com/oneapi-src/SYCLomatic/pull/980
