### ISSUE TITLE
convert deviceProp.totalConstMem

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#369]
DPCT1051:29: SYCL does not support the device property that would be functionally compatible with totalConstMem. It was migrated to 0. You may need to rewrite the code.

Is `info::device::max_constant_buffer_size` proper for the conversion ?  
https://github.com/intel/llvm/issues/7509

**Comment by keryell** [comment]
Cf my answer on potential better solution https://github.com/intel/llvm/issues/7509#issuecomment-1331119014

**Comment by tomflinda** [comment]
@zjin-lcf, we plan to migrate `deviceProp.totalConstMem` to `deviceProp.get_global_mem_size()`, here get_global_mem_size() is helper function defined in https://github.com/oneapi-src/SYCLomatic/blob/48d3c60a87c036ba2d1a091d24997dbf7e7d7417/clang/runtime/dpct-rt/include/device.hpp.inc#L263

**Comment by zjin-lcf** [comment]
Is the size of a constant memory the same as the size of a global memory ?

**Comment by tomflinda** [comment]
@zjin-lcf yes, https://github.com/oneapi-src/SYCLomatic/pull/417 has been filed to implement this feature.
