### ISSUE TITLE
Certain CUDA functions are not migrated 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#404]
The following function is not migrated after running DPCT. 
Please see the example https://github.com/zjin-lcf/HeCBench/blob/master/prefetch-cuda/main.cu 
The SYCL program is https://github.com/zjin-lcf/HeCBench/blob/master/prefetch-sycl/main.cpp. If it doesn't look right, please let me know. Thanks.

```
  CUDACHECK(cudaDeviceGetAttribute(&concurrentManagedAccess,
        cudaDevAttrConcurrentManagedAccess,
        p_gpuDevice));
```

**Comment by tomflinda** [comment]
@zjin-lcf, the mapping APIs in the SYCL program LGTM.

We will plan to migrate it to 
```
CUDACHECK((concurrentManagedAccess = dpct::dev_mgr::instance().get_device(p_gpuDevice).get_info<info::device::usm_shared_allocations>(), 0));
```
on usm.

For noneUSM, there is no mapping API for it, we will emit a warning msg for it.

**Comment by tomflinda** [comment]
@zjin-lcf  https://github.com/oneapi-src/SYCLomatic/pull/423 has been implemented for this feature.
