### ISSUE TITLE
Error: no member named 'x' in 'sycl::range<3>

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#412]
Please use the zipped CUDA program to reproduce the error. Thanks. 

[dpct_reproducer.zip](https://github.com/oneapi-src/SYCLomatic/files/10213851/dpct_reproducer.zip)

**Comment by tomflinda** [comment]
Pls follow the steps in https://github.com/oneapi-src/SYCLomatic/issues/413.
For this issue, pls specify option `--use-experimental-features=free-function-queries` to do migration:
```
unzip dpct_reproducer.zip
cd dpct_reproducer/
dpct -out-root out1 main.cu --use-experimental-features=free-function-queries
```

**Comment by zjin-lcf** [comment]
Thanks.
