### ISSUE TITLE
Error: parameter of overloaded post-increment operator must have type 'int' (not 'sycl::nd_item<3>')

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#413]
Please use the zipped CUDA program to reproduce the error. Thanks.
[dpct_reproducer.zip](https://github.com/oneapi-src/SYCLomatic/files/10213854/dpct_reproducer.zip)

**Comment by tomflinda** [comment]
@zjin-lcf ,
for the reproducer:
1. pls specify option ` --use-experimental-features=free-function-queries` to do migration:
```
unzip dpct_reproducer.zip
cd dpct_reproducer/
dpct -out-root out1 main.cu --use-experimental-features=free-function-queries
```
2. in the migrated file out/block_stride_range.hpp Line14~17:
Pls change the code snippet:
```
namespace detail {
    using dim3_member_type = decltype(sycl::range<3>::x);
    using uint3_member_type = decltype(sycl::uint3::x);
}
```
to
```
namespace detail {
    using dim3_member_type = decltype(std::declval<sycl::range<3>>().get(0));
    using uint3_member_type = sycl::uint3::element_type;
}
```
Then the migrated code could be compiled and built out binary with intel dpcpp compiler.

And for bullet2, it is a bug, we will plan to fix it.
Thanks.

**Comment by zjin-lcf** [comment]
I replaced the "block_stride_range" in the kernel with a plain statement that is equivalent to the logic implemented in block_stride_range. However, I felt that I needed to report the issue. People might try to migrate Cuda programs in OpenCV.  Thanks.

**Comment by tomflinda** [comment]
BTW, for bullet2, https://github.com/oneapi-src/SYCLomatic/pull/460 has been merged to fix it.
