### ISSUE TITLE
compile error : error C2466: cannot allocate an array of constant size 0

### ISSUE THREAD

**Issue by ytzhang1** [oneapi-src/SYCLomatic#424]
Hi, I'm compiling SYCLomatic on Windows, using the nmake system, but get the following error near the end, any idea what might be wrong ?

[100%] Building CXX object tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/Homoglyph.cpp.obj
cl : Command line warning D9025 : overriding '/MD' with '/MT'
Homoglyph.cpp
...\SYCLomatic\build\tools\clang\lib\DPCT\Confusables.inc(1): error C2466: cannot allocate an array of constant size 0
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

**Comment by ytzhang1** [comment]
Here's what's contained in the Confusables.inc file,


struct {llvm::UTF32 codepoint; llvm::UTF32 values[32];} ConfusableEntries[] = {
};

**Comment by tomflinda** [comment]
@ytzhang1 Thanks for your report, we will do a further investigation.

**Comment by intwanghao** [comment]
@ytzhang1 hello, I think you can try to set the git configure core.autocrlf to true, then re-checkout code and re-build dpct.

**Comment by ytzhang1** [comment]
Thanks! that fixed the issue!

**Comment by ytzhang1** [comment]
close it.
