### ISSUE TITLE
migrate max grid sizes

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#462]
In the DPCT header, the grid sizes are set with the default values. The sizes may mismatch the values returned by the CUDA API.

```
DPCT
    int max_nd_range_size[] = {0x7FFFFFFF, 0x7FFFFFFF, 0x7FFFFFFF};
    prop.set_max_nd_range_size(max_nd_range_size);

CUDA
#include <stdio.h>
#include <cuda_runtime.h>
int main(){
  cudaDeviceProp devProp;
  cudaGetDeviceProperties(&devProp, 0);
  printf("%d\n", devProp.maxGridSize[0]);
  printf("%d\n", devProp.maxGridSize[1]);
  printf("%d\n", devProp.maxGridSize[2]);
}
```

**Comment by tomflinda** [comment]
@zjin-lcf  from the cuda side, the values of grid sizes depend on the device it runs(by calling cudaGetDeviceProperties()), while in SYCL side, max_nd_range_size has no such limitation.
So, it is not a issue for cuda to SYCL migration.

**Comment by zjin-lcf** [comment]
I submit a feature request at LLVM. It is not certain whether the maximum values should match.

**Comment by tomflinda** [comment]
@zjin-lcf ok, BTW, pls provide your request URL, so that we can follow up its status.

**Comment by zjin-lcf** [comment]
https://github.com/intel/llvm/issues/7899

**Comment by tomflinda** [comment]
@zjin-lcf thanks your info, I will close it as not planned.
