### ISSUE TITLE
compile error: no member named 'l2CacheSize' in 'dpct::device_info'

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#516]
cudaDeviceProp properties;
        result = cudaGetDeviceProperties(&properties, 0);
        std::cout << "L2 Cache Size: " << properties.l2CacheSize / 1024 / 1024 << " MB" << std::endl;

postnote
https://github.com/intel/llvm/issues/8093

**Comment by tomflinda** [comment]
@zjin-lcf it will be implemented when the mapping API is available in the SYCL compiler side.

**Comment by zjin-lcf** [comment]
I think that the SYCL spec committee will add more device info to the spec first. Is that right ?

**Comment by tomflinda** [comment]
@zjin-lcf I think so, or it will be added into `https://github.com/intel/llvm/tree/sycl/sycl/doc/extensions/proposed` first.
