### ISSUE TITLE
DPCT1101: 'BLOCK_SIZE' expression was replaced with a value

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#521]
DPCT will replace a used-defined macro with the value in the SYCL program when migrating a CUDA program. Could you please explain the reason ?  

As you know, without a macro, users have to modify all values, if needed, in a program.
 
Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf, usually DPCT uses used-defined macro instead of the value in the migrated code to avoid the case that users have to modify all values in the migrated code if needed. 
So, could you please provide a simple self-contain reproducer for this issue?
Thanks.

**Comment by zjin-lcf** [comment]
```
#define BLOCK_SIZE 256

__global__ void k (int *x, int *y) {
  __shared__ int sm [BLOCK_SIZE];
}

int main() {
  int *x, *y;
  cudaMalloc((void**)&x, BLOCK_SIZE * 1024);
  cudaMalloc((void**)&y, BLOCK_SIZE * 1024);
  k<<<BLOCK_SIZE, BLOCK_SIZE>>>(x, y);
  cudaFree(x);
  cudaFree(y);
}
```

In the generated code, the comment suggests code modification for the size of a local memory. Could you please explain the macro replacement ?  Thanks. 

```
    /*
    DPCT1101:0: 'BLOCK_SIZE' expression was replaced with a value. Modify the
    code to use original expression, provided in comments, if it is correct.
    */
    sycl::local_accessor<int, 1> sm_acc_ct1(sycl::range<1>(256 /*BLOCK_SIZE*/),
                                            cgh);
```

**Comment by tomflinda** [comment]
@zjin-lcf ,The usage location of the macro  `BLOCK_SIZE` was moved from the definition of k() to the call-site of k() in the migrated code to avoid the potential compile error, so the macro `BLOCK_SIZE` was replaced with the value.

And if you want to keep the macro  `BLOCK_SIZE`  in the migrated code, you can specify the option `--use-experimental-features=local-memory-kernel-scope-allocation` in the migration command.
