### ISSUE TITLE
[question] migrate __restrict__ in CUDA kernel

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#534]
Is `__restrict__` the same as `__restrict` when DPCT does not make the conversion ?   Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf 
1. `__restrict__` has the same semantics  as `__restrict`
2. `__restrict__` and `__restrict` are both supported by nvcc and SYCL compiler
So, DPCT does not migrate them.
