### ISSUE TITLE
Two expressions do not provide the exact same functionality

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#548]
I think the functionality is the same for the following two expressions. Is that right ? Thanks.
```
DPCT1098:
The ((upsample(hi, lo) << min(shift, 32)) >> 32) expression is used instead of the __funnelshift_lc call. These two expressions do not
provide the exact same functionality.
```

**Comment by tomflinda** [comment]
@zjin-lcf In theory, the two functions only have potential precision and/or performance issues.

**Comment by zjin-lcf** [comment]
More specifically, what is the performance issue ?  Note that the comments are not displayed when migrating other CUDA integer intrinsic functions.

**Comment by tomflinda** [comment]
@zjin-lcf current migration is use the emulate method, so it may introduce extra cost which depends on and compiler and HW.

**Comment by zjin-lcf** [comment]
Is it ok to propose the addition of funnel shift functions to the SYCL specification ?

**Comment by tomflinda** [comment]
@zjin-lcf  I think so.
I close this issues now, and free to reopen it, if you have further concerns.
