### ISSUE TITLE
DPCT1051: support the query of a device ID

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#572]
For the Cuda program, the migration comment is "SYCL does not support the device property that would be functionally compatible with pciDeviceID. It was migrated to -1".  Thanks.

```
int main() {
  cudaDeviceProp p;
  cudaGetDeviceProperties(&p, 0);
  std::cout << "device ID " << p.pciDeviceID << "\n";
}
```

**Comment by tomflinda** [comment]
@zjin-lcf SYCL side cannot prove PCI device ID, that's why DPCT emits the warning message. So what's your requirement?

**Comment by zjin-lcf** [comment]
I find the sycl function for migration:

auto deviceID = gpu.get_info<sycl::ext::intel::info::device::device_id>();

**Comment by tomflinda** [comment]
@zjin-lcf thanks for your info, yes,[ Intel's Extensions for Device Information](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md) has provide the mapping, we will plan to implement it.

**Comment by zjin-lcf** [comment]
Thanks.
