### ISSUE TITLE
support device UUID query

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#573]
Please see the example.  Thanks.

```
void uuid_print(cudaUUID_t a){}

int main() {
  cudaDeviceProp p;
  cudaGetDeviceProperties(&p, 0);
  uuid_print(p.uuid);
}
```

**Comment by tomflinda** [comment]
@zjin-lcf there is no device uuid concept in SYCL side according to SYCL 2020 spec.

**Comment by zjin-lcf** [comment]
I find the sycl function for migration:

```
auto deviceID = gpu.get_info<sycl::ext::intel::info::device::uuid_id>();
```

**Comment by tomflinda** [comment]
@zjin-lcf thanks for your info, yes, [Intel's Extensions for Device Information](https://github.com/intel/llvm/blob/sycl/sycl/doc/extensions/supported/sycl_ext_intel_device_info.md) has provided the mapping.
So we will plan to implement it.

**Comment by zjin-lcf** [comment]
Thanks.
