### ISSUE TITLE
fatal error: LLVMSPIRVLib.h: No such file or directory

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#583]
I tried to build the software and got the following error.

To reproduce (note Ninja is not available)
```
cmake -DCMAKE_INSTALL_PREFIX=$PATH_TO_C2S_INSTALL_FOLDER  -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_PROJECTS="clang"  -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" ../SYCLomatic/llvm


/$HOME/workspace/SYCLomatic/llvm/tools/spirv-to-ir-wrapper/spirv-to-ir-wrapper.cpp:22:10: fatal error: LLVMSPIRVLib.h: No such file or directory
   22 | #include "LLVMSPIRVLib.h"

```
Do I need to install additional dependency that is not already listed ? Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf  could you provide the complete build command?

**Comment by zjin-lcf** [comment]
```
export SYCLOMATIC_HOME=~/workspace
export PATH_TO_C2S_INSTALL_FOLDER=~/workspace/c2s_install
mkdir $SYCLOMATIC_HOME
cd $SYCLOMATIC_HOME

git clone https://github.com/oneapi-src/SYCLomatic.git

cd $SYCLOMATIC_HOME
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$PATH_TO_C2S_INSTALL_FOLDER  -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_PROJECTS="clang"  -DLLVM_TARGETS_TO_BUILD="X86;NVPTX" ../SYCLomatic/llvm
make -j
```

**Comment by tomflinda** [comment]
@zjin-lcf , thanks for your info, I have reproduced it, it is an unexpected behavior, we will plan to fix it.

**Comment by zjin-lcf** [comment]
No problem.

**Comment by tomflinda** [comment]
@zjin-lcf after a further thought, in SYCLomatic code repo we only maintain make target "install-dpct, install-c2s, check-clang-dpct, check-clang-c2s" for our compatibility tool,  so in your last build command `make -j`, should use `make -j target_name`, target_name could be one of `install-dpct, install-c2s, check-clang-dpct, check-clang-c2s`, then the build process should pass.

**Comment by zjin-lcf** [comment]
What are the differences between the "dpct" and "c2s" targets ?  Thanks.

**Comment by tomflinda** [comment]
@zjin-lcf no differences in functionality.
