### ISSUE TITLE
DPCT1013  rounding modes could not be specified 

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#585]
Migrating the cuda file shows the DPCT1013 message. 
https://github.com/NVIDIA/cuda-samples/blob/master/Samples/2_Concepts_and_Techniques/interval/cuda_interval_rounded_arith.h

Does SYCL support different rounding modes ?   I'd like to submit a request to Intel LLVM if they are not supported. Thanks.

DPCT1013:12: The rounding mode could not be specified and the generated code
    may have different precision then the original code

**Comment by tomflinda** [comment]
@zjin-lcf in SYCL 2020 spec, there is no different rounding  mode version for one math API.
