### ISSUE TITLE
Possible overflow in `matrix_mem_copy`

### ISSUE THREAD

**Issue by TApplencourt** [oneapi-src/SYCLomatic#591]
Hi,

This line may overflow int before being casted to `size_t`:

https://github.com/oneapi-src/SYCLomatic/blob/73b5c1225e0ae5d93d7f4c8193a1ec9b1eccc0de/clang/runtime/dpct-rt/include/util.hpp.inc#LL112

One solution is to `cast` on elements to `size_t`: `size_t cpoy_size = elem_size * ((cols - 1) * (size_t) to_ld + rows);`
The other is to change the signature of the function to take `size_t` as arguments (and not `int`)

This impacted some of our application (made L0 segfaulting)

**Comment by zjin-lcf** [comment]
Does it happen when you migrate the cudaMemcpy() function ?

**Comment by TApplencourt** [comment]
I think `cudaMemcpy2D`, but not sure.
The code I work with use directly `matrix_mem_copy` because it's lacking in sycl.

**Comment by zjin-lcf** [comment]
Okay. A feature request to Intel LLVM / SYCL specification.  Thanks.

**Comment by zjin-lcf** [comment]
This may be relevant to your evaluation: https://github.com/intel/llvm/pull/8181

**Comment by tomflinda** [comment]
@zjin-lcf we will take the first solution `to cast on elements to size_t: size_t cpoy_size = elem_size * ((cols - 1) * (size_t) to_ld + rows)` to keep the API's signature unchanged.

**Comment by zjin-lcf** [comment]
Thanks.

**Comment by tomflinda** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/697 has fixed this issue.
