### ISSUE TITLE
Migration of thrust::reverse is not supported

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#618]
The error, which was reported in https://github.com/oneapi-src/SYCLomatic/issues/570, is also observed when migrating the `thrust::reverse`. Thanks. 

```
#include <thrust/reverse.h>
#include <thrust/device_vector.h>
#include <thrust/execution_policy.h>

int main() {
const int N = 6;
int data[N] = {0, 1, 2, 3, 4, 5};
thrust::device_vector<int> v(data, data + N);
thrust::reverse(thrust::device, v.begin(), v.end());
}
```

**Comment by tomflinda** [comment]
@zjin-lcf, we will plan to implement it when the mapping API from oneDPL libary has provided, we will sync it with oneDPL team,  thanks.

**Comment by zjin-lcf** [comment]
I see.

**Comment by tomflinda** [comment]
This feature issue has been implemented by https://github.com/oneapi-src/SYCLomatic/pull/786, so close it.
