### ISSUE TITLE
Email received whenever a comment/reply is made

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#703]
I will receive an email when a comment/reply is made for issues. Not sure if others receive it too. Could the test system stop sending an email ? Thanks.

<html>
<body>

[oneapi-src/SYCLomatic] .github/workflows/windows_test_comment_trigger.yml workflow run | [oneapi-src/SYCLomatic] .github/workflows/windows_test_comment_trigger.yml workflow run |  
-- | -- | --
[oneapi-src/SYCLomatic] .github/workflows/windows_test_comment_trigger.yml workflow run
 

</body>
</html>[oneapi-src/SYCLomatic] .github/workflows/windows_test_comment_trigger.yml workflow run
 

 
.github/workflows/windows_test_comment_trigger.yml: No jobs were run
 
[View workflow run](https://github.com/oneapi-src/SYCLomatic/actions/runs/4316488947)

**Comment by tomflinda** [comment]
@kathywar do you know how to fix this kind of issue?

**Comment by kathywar** [comment]
> @kathywar do you know how to fix this kind of issue?

Have you gone to Settings ... Notifications and then customize by unchecking the boxes shown below?

<img width="387" alt="image" src="https://user-images.githubusercontent.com/51721121/222778834-6751aaf7-e761-42af-ac6c-e4e5ceef78dc.png">

**Comment by zjin-lcf** [comment]
Thanks
