### ISSUE TITLE
compile error: FAILED: tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/Homoglyph.cpp.obj

### ISSUE THREAD

**Issue by ciaranmurraycm** [oneapi-src/SYCLomatic#808]
**Describe the bug**
Build on WIndows 11 using VS 2022 fails

[1790/1898] Generating Confusables.inc
::::::
[1836/1898] Building CXX object tools\clang\lib\DPCT\CMakeFiles\obj.DPCT.dir\Homoglyph.cpp.obj
FAILED: tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/Homoglyph.cpp.obj

**To Reproduce**
Just follow build instructions in readme.md

1. Include code snippet as short as possible : N/A
2. Specify the command which should be used to compile the program N/A
3. Specify the comment which should be used to launch the program N/A
4. Indicate what is wrong and what was expected : ABOVE

**Environment (please complete the following information):**

- OS: [e.g Windows/Linux]  Windows 11
- Target device and vendor: [e.g. Intel GPU] N/A
- DPC++ version: [e.g. commit hash or output of `clang++ --version`]
- Dependencies version: [e.g. low-level runtime versions (like NEO 20.04)]
- Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.5.3

**Additional context**

Will try Ubuntu 22.04 under WSL also

**Comment by ciaranmurraycm** [comment]
Also fails on ubuntu 22.04 with g++ 11.3.0

:::::
[1797/1891] Generating Confusables.inc
Parsed 6311 Entries
[1808/1891] Building CXX object tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/CallExprRewriterThrust.cpp.o
FAILED: tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/CallExprRewriterThrust.cpp.o
/usr/bin/c++ -DENABLE_OPAQUE_POINTERS=1 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/mnt/d/ciaran/development/Cxx/parallel/sycl/_build_u22/tools/clang/lib/DPCT -I/mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/clang/lib/DPCT -I/mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/llvm/../llvm-spirv/include -I/mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/clang/include -I/mnt/d/ciaran/development/Cxx/parallel/sycl/_build_u22/tools/clang/include -I/mnt/d/ciaran/development/Cxx/parallel/sycl/_build_u22/include -I/mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/llvm/include -I/mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/clang/lib/DPCT/../../../clang/lib/Driver -DSYCLomatic_CUSTOMIZATION=1 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-cast-function-type -Wno-parentheses -Wno-uninitialized -Wno-unused-function -Wno-redundant-move -Wno-init-list-lifetime -Wno-deprecated-copy -Wno-write-strings -Wno-array-bounds -Wno-pessimizing-move -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG -std=c++17 -MD -MT tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/CallExprRewriterThrust.cpp.o -MF tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/CallExprRewriterThrust.cpp.o.d -o tools/clang/lib/DPCT/CMakeFiles/obj.DPCT.dir/CallExprRewriterThrust.cpp.o -c /mnt/d/ciaran/development/Cxx/parallel/sycl/SYCLomatic/clang/lib/DPCT/CallExprRewriterThrust.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
::::

**Comment by tomflinda** [comment]
@ciaranmurraycm could your provide the system memory capacity in your machine? and the -jNumber for your ninja build command.
Usually,  for build system with 16G or less memory, to avoid out of memory issues, it is recommended to add the option -DLLVM_PARALLEL_LINK_JOBS=1 in the CMake step and use 4 or less total parallel jobs when building SYCLomatic by invoking ninja with the option -j4.
More detail, pls refer to https://github.com/oneapi-src/SYCLomatic/blob/SYCLomatic/README.md.

**Comment by ciaranmurraycm** [comment]
Hello tomflinda.
Build machine has 64Gb memory, i9 (24 logical processors) .... ninja used default (which I assume is -j 24 )
(On Ubuntu max memory is 16 GB but it is rarely above 6 Gb )

Note on  Windows build : Confusables.inc has 0 entries ... yet had 6311 on Ubuntu build

**Comment by tomflinda** [comment]
For build on ubuntu, pls try to build SYCLomatic with ninja -j12 in you machine with  64Gb memory and i9 processor.
For Windows build,  try to set the git configure core.autocrlf to true, then re-checkout code and re-build dpct,  which is a known issue reported by https://github.com/oneapi-src/SYCLomatic/issues/424

**Comment by ciaranmurraycm** [comment]
Hi
In Windows git config already has core.autocrlf=true
Ubuntu build using -j 12 ... worked perfectly .... many thanks

**Comment by tomflinda** [comment]
@ciaranmurraycm My pleasure, if you meet other issues during migration, feel free to file issues to us.
