### ISSUE TITLE
Migration of __assert_fail is not supported

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#831]
When a host program contains the "assert()" function, it may be ignored by the translator. The warning may be confusing. Thanks. 

```
  /*
  DPCT1007:34: Migration of __assert_fail is not supported.
  */
  assert(f == 1);
```

**Comment by tomflinda** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/834 will fix this issue.

**Comment by zjin-lcf** [comment]
Thanks.
