### ISSUE TITLE
DPCT internal error may be caused by thrust::cuda::par.on(stream)

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#906]
thrust::for_each(
            thrust::cuda::par.on(stream),

The above code snippet is not migrated, which may cause DPCT internal error.

Reference
https://github.com/BioinfoSZU/CURC/blob/master/src/compress.cu

**Comment by tomflinda** [comment]
@zjin-lcf  I will take a further investigation.

**Comment by tomflinda** [comment]
@zjin-lcf this issue has been reproduced, root cause is identified, we will plan to fix it.

**Comment by zjin-lcf** [comment]
Thank you for your update.

**Comment by Chemnovo1** [comment]
I'm interested in SYCLomatic tool and SYCL, and have spent some time to learn its code, and plan to fix this bug issue.

**Comment by Chemnovo1** [comment]
Patch has been submitted
https://github.com/oneapi-src/SYCLomatic/pull/918

**Comment by zjin-lcf** [comment]
Thank you for your patch.

**Comment by tomflinda** [comment]
@zjin-lcf , the PR for this issue is still in alloy test, not reviewed. After it is reviewed pass and merged, then this issue can be closed.

**Comment by tomflinda** [comment]
@Chemnovo1 thanks for submitting the PR for this issue and thanks for your interest in SYCLomatic  , after it passes the alloy test, we will review it ASAP.

**Comment by tomflinda** [comment]
@Chemnovo1 your PR https://github.com/oneapi-src/SYCLomatic/pull/918 has been merged, so I have closed this issue. 
Also, welcome to submitting new PRs for other issues that you are interested in and plan to fix them.
