### ISSUE TITLE
hang when executing matrix transpose

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/SYCLomatic#907]
After migrating the file https://github.com/zjin-lcf/HeCBench/blob/master/geam-cuda/main.cu from CUDA to SYCL, running the SYCL program hangs on an Intel device (0x56a0). Thanks.

Reference
https://github.com/oneapi-src/oneMKL/issues/183

**Comment by tomflinda** [comment]
@zjin-lcf in my local machine, it run passed with the following commands on device cpu:
```
cd HeCBench/geam-cuda/
intercept-build make
dpct -in-root ./ -out-root out -p ./ -gen-build-script
cd out
make -f Makefile.dpct
./main 20 20 10
```
So, pls provide what device you used, cpu device or gpu device?  Also the test command and SYCLomatic version

**Comment by zjin-lcf** [comment]
Thanks for the commands.

compiler version: Intel(R) oneAPI DPC++/C++ Compiler 2023.0.0 (2023.0.0.20221201)

command:  ./main 16384 16384 200

DSYCLomatic version: dpct version 17.0.0. Codebase:(66842b98165dab42b4c593371bdb6857bce3c87a)

GPU device: 0x56a0

**Comment by tomflinda** [comment]
@zjin-lcf in your machine, if you run command :  "./main 20 20 10", can the app run passed?

**Comment by zjin-lcf** [comment]
Yes

**Comment by tomflinda** [comment]
@zjin-lcf it should be a bug of mkl function “oneapi::mkl::blas::column_major::omatadd”,  advise you to open a new issue in https://github.com/oneapi-src/oneMKL/issues/, so that you can track the status.
And for the reproducer, you can apply the modification below to remove the dependency of SYCLomatic helper header files:
```
diff --git a/main.dp.cpp b/main.dp.cpp
index e659492..b4fd42f 100644
--- a/main.dp.cpp
+++ b/main.dp.cpp
@@ -1,14 +1,13 @@
 #include <sycl/sycl.hpp>
-#include <dpct/dpct.hpp>
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 #include <chrono>
-#include <dpct/blas_utils.hpp>
+#include <oneapi/mkl.hpp>
+
+sycl::queue q_ct1;

 template <typename T> void transpose_f64(int nrow, int ncol, int repeat) try {
-  dpct::device_ext &dev_ct1 = dpct::get_current_device();
-  sycl::queue &q_ct1 = dev_ct1.default_queue();
   int error = 0;
   const size_t size = nrow * ncol;
   const size_t size_byte = size * sizeof(T);
@@ -29,7 +28,7 @@ template <typename T> void transpose_f64(int nrow, int ncol, int repeat) try {
   printf("Host: serial matrix transpose time = %f (ms)\n", time * 1e-6f);

   int stat;
-  dpct::queue_ptr handle;
+  sycl::queue * handle;
   handle = &q_ct1;

   const T alpha = (T)1;
@@ -60,7 +59,7 @@ template <typename T> void transpose_f64(int nrow, int ncol, int repeat) try {
                 oneapi::mkl::transpose::nontrans, nrow, ncol, alpha, d_matrix,
                 ncol, beta, d_matrix, nrow, d_matrixT, nrow),
             0);
-    dev_ct1.queues_wait_and_throw(); // required for timing correctness
+    q_ct1.wait(); // required for timing correctness
     if (i >= warmup) {
       end = std::chrono::steady_clock::now();
       time += std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
@@ -97,8 +96,6 @@ catch (sycl::exception const &exc) {
 }

 template <typename T> void transpose_f32(int nrow, int ncol, int repeat) try {
-  dpct::device_ext &dev_ct1 = dpct::get_current_device();
-  sycl::queue &q_ct1 = dev_ct1.default_queue();
   int error = 0;
   const size_t size = nrow * ncol;
   const size_t size_byte = size * sizeof(T);
@@ -119,7 +116,7 @@ template <typename T> void transpose_f32(int nrow, int ncol, int repeat) try {
   printf("Host: serial matrix transpose time = %f (ms)\n", time * 1e-6f);

   int stat;
-  dpct::queue_ptr handle;
+  sycl::queue* handle;
   handle = &q_ct1;

   const T alpha = (T)1;
@@ -149,7 +146,7 @@ template <typename T> void transpose_f32(int nrow, int ncol, int repeat) try {
                 oneapi::mkl::transpose::nontrans, nrow, ncol, alpha, d_matrix,
                 ncol, beta, d_matrix, nrow, d_matrixT, nrow),
             0);
-    dev_ct1.queues_wait_and_throw(); // required for timing correctness
+    q_ct1.wait(); // required for timing correctness
     if (i >= warmup) {
       end = std::chrono::steady_clock::now();
       time += std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();

```

**Comment by zjin-lcf** [comment]
Thank you for the instructions.

**Comment by andrewtbarker** [comment]
I cannot reproduce this on either Intel GPU Max or Intel Arc Alchemist A770 architectures, everything runs fine with the given problem sizes. @zjin-lcf are you satisfied with the resolution here or is this still an issue?

**Comment by zjin-lcf** [comment]
I tried to run the example "geam" with your suggested MKL function on an NVIDIA GPU. The error message is

terminate called after throwing an instance of 'oneapi::mkl::unimplemented'
  what():  oneMKL: blas/omatcopy: function is not implemented for row_major layout

Thanks

**Comment by andrewtbarker** [comment]
@zjin-lcf The wrappers for the cublas backend just haven't been put in yet for that function. We will eventually include them, but if you want to speed up the process, we would consider a pull request to add them.

To add them, what you need to do is basically replace the "unimplemented" place holder [here](https://github.com/oneapi-src/oneMKL/blob/develop/src/blas/backends/cublas/cublas_extensions.cpp#L547) with cublas wrappers like what we do for [gemm](https://github.com/oneapi-src/oneMKL/blob/develop/src/blas/backends/cublas/cublas_level3.cpp#L38-L54), using the appropriate arguments for `geam` instead of `gemm`.
