### ISSUE TITLE
c2s - fatal error: 'cmath' file not found

### ISSUE THREAD

**Issue by cabelo** [oneapi-src/SYCLomatic#919]
When I went to run the c2s command on SUSE I got this error below:

$ c2s vecAdd.cu  
NOTE: Could not auto-detect compilation database for file 'vecAdd.cu' in '/dados/home/space_disk/Intel/exemplo' or any parent directory.
The directory "dpct_output" is used as "out-root"
Processing: /dados/home/space_disk/Intel/exemplo/vecAdd.cu
In file included from <built-in>:1:
In file included from /dados/home/space_disk/Intel/c2s_install/lib/clang/17/include/__clang_cuda_runtime_wrapper.h:42:
/dados/home/space_disk/Intel/c2s_install/lib/clang/17/include/cuda_wrappers/cmath:27:15: fatal error: 'cmath' file not found
#include_next <cmath>
             ^~~~~~~
/dados/home/space_disk/Intel/exemplo/vecAdd.cu:49:5: warning: DPCT1049:0: The work-group size passed to the SYCL kernel may exceed the limit. To get the device limit, query info::device::max_work_group_size. Adju
st the work-group size if needed.
   vecAdd<<<gridSize, blockSize>>>(d_a, d_b, d_c, n);
   ^
Processed 1 file(s) in -in-root folder "/dados/home/space_disk/Intel/exemplo"

**Comment by tomflinda** [comment]
@cabelo firstly pls make sure your vecAdd.cu case could be compiled by nvcc.
if it could be compiled, and you still meet this issue during migration.
Pls provide a standalone reproducer, the distribution version of your host SUSE OS, the version of c2s and g++, so that we can reproduce your issue and do a further investigation.
Thanks.

**Comment by cabelo** [comment]
Yes, my vecAdd.cu case could be compiled by nvcc. Bellow evidence.
![syclomatic](https://github.com/oneapi-src/SYCLomatic/assets/675645/53e4f7fc-7425-4c62-ae66-c9a23f588012)

**Comment by cabelo** [comment]
My version of host SUSE OS bellow:

cat /etc/os-release 
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"

**Comment by cabelo** [comment]
The version of c2s and g++ Bellows:
c2s = git clone https://github.com/oneapi-src/SYCLomatic

gcc version 7.5.0 (SUSE Linux) 

Thanks

**Comment by tomflinda** [comment]
@cabelo on same Linux distribution, I cannot reproduce this issue with test code https://github.com/oneapi-src/oneAPI-samples/blob/master/Tools/Migration/vector-add-dpct/src/vector_add.cu

So, pls attach a simple reproducer.

**Comment by tomflinda** [comment]
@haberman sorry, typo, have updated the msg.

**Comment by tomflinda** [comment]
@cabelo could you provide a simple reproducer? so that we can reproduce this issue and do further investigation.

**Comment by cabelo** [comment]
Hi @tomflinda 

 

I was using SUSE Enterprise 15-SP3, when I upgraded to 15-SP4 everything worked. Thank you for your support and attention.

Everything is ok now.
